version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    #   target: base
    volumes:
      - ./src:/app/src/
      - ./nodemon.json:/app/nodemon.json
    container_name: toolbox-api
    expose:
      - '8888'
    ports:
      - '8888:8888'
    command: npm run start
