version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    #   target: base
    volumes:
      - ./src:/app/src/
    container_name: toolbox-api
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
